variables:
  IMAGE_NAME: cplpublic/gcloud-terraform
  IMAGE_TAG: dev

image:
  name: gcr.io/kaniko-project/executor:v1.3.0-debug
  entrypoint: [""]

.build_image:
  script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "$(echo -n "$DOCKER_HUB_USER:$DOCKER_HUB_PASSWORD" | base64)"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --dockerfile "Dockerfile"
      --context "."
      --destination $IMAGE_NAME:$IMAGE_TAG

build_master:
  extends: .build_image
  variables:
    IMAGE_TAG: latest
  only:
    - master

build_tag:
  extends: .build_image
  variables:
    IMAGE_TAGE: $CI_COMMIT_TAG
  only:
    - tags
